# -*- coding: utf-8 -*-
"""Untitled179.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vhcCWlOH2hbysiu5BjaKgaKRzsOoqW_6
"""

# ============================================================
# Arabic News Text Classification
# Classical and Neural Models: SVM, DNN, and CNN-LSTM
# Updated Professional Research Code
# ============================================================

# -----------------------------
# 1. Imports and Configuration
# -----------------------------

import os
import re
import random
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import nltk
from nltk.stem.isri import ISRIStemmer
from nltk.corpus import stopwords

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer, TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC, LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
    classification_report,
    confusion_matrix,
    roc_auc_score,
)

import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.layers import (
    Input,
    Embedding,
    GlobalAveragePooling1D,
    Dense,
    Conv1D,
    MaxPooling1D,
    Dropout,
    LSTM,
)
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

warnings.filterwarnings("ignore")


# -----------------------------
# 2. Reproducibility Settings
# -----------------------------

SEED = 5
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)


# -----------------------------
# 3. Experiment Configuration
# -----------------------------

# Update this path if your CSV is stored somewhere else.
# The code below also tries common local/Colab paths automatically.
DATA_PATH = "arabic_dataset_classifiction.csv"
TEXT_COLUMN = "text"
LABEL_COLUMN = "targe"

OUTPUT_DIR = Path("arabic_text_classification_outputs")
FIGURE_DIR = OUTPUT_DIR / "figures"
MODEL_DIR = OUTPUT_DIR / "models"

OUTPUT_DIR.mkdir(exist_ok=True)
FIGURE_DIR.mkdir(exist_ok=True)
MODEL_DIR.mkdir(exist_ok=True)

# Data and model parameters
SAMPLES_PER_CLASS = 10000
TEST_SIZE = 0.20
VALIDATION_SIZE = 0.20

MAX_NB_WORDS = 20000
MAX_SEQUENCE_LENGTH = 300
EMBEDDING_DIM = 50
BATCH_SIZE = 128
EPOCHS = 15

TFIDF_MAX_FEATURES = 5000


# -----------------------------
# 4. Utility Functions
# -----------------------------

def download_nltk_resources():
    """Download required NLTK resources."""
    nltk.download("stopwords", quiet=True)


def find_dataset_file(data_path: str) -> str:
    """Find the dataset file from common local and Colab locations."""
    candidate_paths = [
        data_path,
        "arabic_dataset_classifiction.csv",
        "./arabic_dataset_classifiction.csv",
        "/content/arabic_dataset_classifiction.csv",
        "/mnt/data/arabic_dataset_classifiction.csv",
    ]

    for path in candidate_paths:
        if os.path.exists(path):
            return path

    # Search recursively in the current working directory.
    matches = list(Path(".").rglob("arabic_dataset_classifiction.csv"))
    if matches:
        return str(matches[0])

    raise FileNotFoundError(
        "Dataset file was not found. Please place arabic_dataset_classifiction.csv "
        "in the same folder as this notebook/script, or update DATA_PATH to the full path."
    )


def load_dataset(data_path: str) -> pd.DataFrame:
    """Load Arabic text classification dataset."""
    data_path = find_dataset_file(data_path)
    print(f"Loading dataset from: {data_path}")

    df = pd.read_csv(data_path)

    if TEXT_COLUMN not in df.columns or LABEL_COLUMN not in df.columns:
        raise ValueError(
            f"Expected columns '{TEXT_COLUMN}' and '{LABEL_COLUMN}'. "
            f"Found columns: {list(df.columns)}"
        )

    df = df[[TEXT_COLUMN, LABEL_COLUMN]].dropna().reset_index(drop=True)
    df[TEXT_COLUMN] = df[TEXT_COLUMN].astype(str)
    df[LABEL_COLUMN] = df[LABEL_COLUMN].astype(str)

    # Remove accidental header-like rows if they exist in concatenated CSV files.
    df = df[df[TEXT_COLUMN].str.lower() != TEXT_COLUMN.lower()].reset_index(drop=True)
    df = df[df[LABEL_COLUMN].str.lower() != LABEL_COLUMN.lower()].reset_index(drop=True)

    return df


def print_dataset_statistics(df: pd.DataFrame, title: str = "Dataset Statistics"):
    """Print basic dataset statistics."""
    num_docs = len(df)
    num_words = df[TEXT_COLUMN].str.split().str.len().sum()
    avg_len = df[TEXT_COLUMN].str.split().str.len().mean()
    max_len = df[TEXT_COLUMN].str.split().str.len().max()
    n_classes = df[LABEL_COLUMN].nunique()

    print("\\n" + "=" * 70)
    print(title)
    print("=" * 70)
    print(f"Number of documents: {num_docs:,}")
    print(f"Number of words: {num_words:,}")
    print(f"Average document length: {avg_len:.2f} words")
    print(f"Maximum document length: {max_len:,} words")
    print(f"Number of classes: {n_classes}")
    print("\\nClass distribution:")
    print(df[LABEL_COLUMN].value_counts())


def balance_dataset(df: pd.DataFrame, samples_per_class: int, seed: int = SEED) -> pd.DataFrame:
    """
    Balance the dataset by sampling a fixed number of documents per class.
    If a class has fewer documents than requested, all available documents are used.
    """
    balanced_parts = []

    for label, group in df.groupby(LABEL_COLUMN):
        n = min(samples_per_class, len(group))
        balanced_parts.append(group.sample(n=n, random_state=seed))

    balanced_df = pd.concat(balanced_parts, axis=0)
    balanced_df = balanced_df.sample(frac=1.0, random_state=seed).reset_index(drop=True)

    return balanced_df


def normalize_arabic(text: str) -> str:
    """Apply light Arabic text normalization."""
    text = str(text)

    # Remove Arabic diacritics and tatweel
    arabic_diacritics = re.compile(r"[\u0617-\u061A\u064B-\u0652]")
    text = re.sub(arabic_diacritics, "", text)
    text = re.sub(r"ـ", "", text)

    # Normalize common Arabic letter variants
    text = re.sub(r"[إأآا]", "ا", text)
    text = re.sub(r"ى", "ي", text)
    text = re.sub(r"ؤ", "و", text)
    text = re.sub(r"ئ", "ي", text)
    text = re.sub(r"ة", "ه", text)

    # Remove URLs, emails, and extra spaces
    text = re.sub(r"http\S+|www\S+", " ", text)
    text = re.sub(r"\S+@\S+", " ", text)
    text = re.sub(r"\s+", " ", text).strip()

    return text


def preprocess_arabic_text(text: str, remove_stopwords: bool = True, stem: bool = True) -> str:
    """Normalize, optionally remove Arabic stopwords, and optionally stem Arabic words."""
    text = normalize_arabic(text)

    words = text.split()

    if remove_stopwords:
        words = [w for w in words if w not in ARABIC_STOPWORDS]

    if stem:
        words = [STEMMER.stem(w) for w in words]

    return " ".join(words)


def plot_history(history, model_name: str):
    """Plot and save training/validation accuracy and loss curves."""
    history_dict = history.history

    # Accuracy key compatibility
    acc_key = "accuracy" if "accuracy" in history_dict else "acc"
    val_acc_key = "val_accuracy" if "val_accuracy" in history_dict else "val_acc"

    plt.figure()
    plt.plot(history_dict[acc_key], label="Train Accuracy")
    plt.plot(history_dict[val_acc_key], label="Validation Accuracy")
    plt.title(f"{model_name}: Accuracy per Epoch")
    plt.xlabel("Epoch")
    plt.ylabel("Accuracy")
    plt.legend()
    plt.tight_layout()
    plt.savefig(FIGURE_DIR / f"{model_name.lower().replace(' ', '_')}_accuracy.png", dpi=300)
    plt.show()

    plt.figure()
    plt.plot(history_dict["loss"], label="Train Loss")
    plt.plot(history_dict["val_loss"], label="Validation Loss")
    plt.title(f"{model_name}: Loss per Epoch")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.legend()
    plt.tight_layout()
    plt.savefig(FIGURE_DIR / f"{model_name.lower().replace(' ', '_')}_loss.png", dpi=300)
    plt.show()


def plot_confusion_matrix(cm, class_names, model_name: str):
    """Plot and save confusion matrix without requiring seaborn."""
    plt.figure(figsize=(8, 6))
    plt.imshow(cm, interpolation="nearest")
    plt.title(f"{model_name}: Confusion Matrix")
    plt.colorbar()
    tick_marks = np.arange(len(class_names))
    plt.xticks(tick_marks, class_names, rotation=45, ha="right")
    plt.yticks(tick_marks, class_names)

    threshold = cm.max() / 2.0
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            plt.text(
                j,
                i,
                format(cm[i, j], "d"),
                ha="center",
                va="center",
                color="white" if cm[i, j] > threshold else "black",
            )

    plt.ylabel("True Label")
    plt.xlabel("Predicted Label")
    plt.tight_layout()
    plt.savefig(FIGURE_DIR / f"{model_name.lower().replace(' ', '_')}_confusion_matrix.png", dpi=300)
    plt.show()


def evaluate_predictions(y_true, y_pred, class_names, model_name: str):
    """Compute and print standard classification metrics."""
    accuracy = accuracy_score(y_true, y_pred)
    precision_macro, recall_macro, f1_macro, _ = precision_recall_fscore_support(
        y_true, y_pred, average="macro", zero_division=0
    )
    precision_weighted, recall_weighted, f1_weighted, _ = precision_recall_fscore_support(
        y_true, y_pred, average="weighted", zero_division=0
    )

    print("\n" + "=" * 70)
    print(f"{model_name} Evaluation")
    print("=" * 70)
    print(f"Accuracy:          {accuracy:.4f}")
    print(f"Macro Precision:   {precision_macro:.4f}")
    print(f"Macro Recall:      {recall_macro:.4f}")
    print(f"Macro F1:          {f1_macro:.4f}")
    print(f"Weighted F1:       {f1_weighted:.4f}")
    print("\nClassification Report:")
    print(classification_report(y_true, y_pred, target_names=class_names, zero_division=0))

    cm = confusion_matrix(y_true, y_pred)
    plot_confusion_matrix(cm, class_names, model_name)

    return {
        "Model": model_name,
        "Accuracy": accuracy,
        "Macro Precision": precision_macro,
        "Macro Recall": recall_macro,
        "Macro F1": f1_macro,
        "Weighted Precision": precision_weighted,
        "Weighted Recall": recall_weighted,
        "Weighted F1": f1_weighted,
    }


def evaluate_neural_model(model, x_test, y_test_categorical, y_test_labels, class_names, model_name: str):
    """Evaluate a Keras neural model."""
    y_prob = model.predict(x_test, verbose=0)
    y_pred = np.argmax(y_prob, axis=1)

    result = evaluate_predictions(y_test_labels, y_pred, class_names, model_name)

    try:
        auc = roc_auc_score(y_test_categorical, y_prob, multi_class="ovr")
        result["AUC_OVR"] = auc
        print(f"AUC OVR:           {auc:.4f}")
    except Exception as e:
        result["AUC_OVR"] = np.nan
        print(f"AUC could not be computed: {e}")

    return result


def create_latex_results_table(results_df: pd.DataFrame, output_path: Path):
    """Create a simple LaTeX table from the result summary."""
    table_df = results_df.copy()
    metric_cols = [c for c in table_df.columns if c != "Model"]
    table_df[metric_cols] = table_df[metric_cols].round(4)

    latex = table_df.to_latex(index=False, escape=False)
    output_path.write_text(latex, encoding="utf-8")
    print(f"LaTeX results table saved to: {output_path}")


# -----------------------------
# 5. Download NLTK Resources
# -----------------------------

download_nltk_resources()
ARABIC_STOPWORDS = set(stopwords.words("arabic"))
STEMMER = ISRIStemmer()


# -----------------------------
# 6. Load and Inspect Dataset
# -----------------------------

# If using Google Colab and the dataset is zipped, uncomment this line:
# !unzip arabic_dataset_classifiction.zip -d .

raw_df = load_dataset(DATA_PATH)
print_dataset_statistics(raw_df, title="Original Dataset Statistics")


# -----------------------------
# 7. Balance Dataset
# -----------------------------

if raw_df[LABEL_COLUMN].nunique() < 2:
    raise ValueError(
        "The loaded dataset contains only one class. This is not a valid classification setup.\\n"
        f"Detected class distribution:\\n{raw_df[LABEL_COLUMN].value_counts()}\\n\\n"
        "Please make sure you are loading the full Arabic text classification CSV with all five classes, "
        "not a single-category CSV or a filtered file. The expected dataset should contain categories such as "
        "culture, economy, sport, politics, and diverse, or numeric labels for all five classes."
    )

balanced_df = balance_dataset(raw_df, samples_per_class=SAMPLES_PER_CLASS, seed=SEED)
print_dataset_statistics(balanced_df, title="Balanced Dataset Statistics")

balanced_df.to_csv(OUTPUT_DIR / "balanced_dataset.csv", index=False)


# -----------------------------
# 8. Train-Test Split
# -----------------------------

train_df, test_df = train_test_split(
    balanced_df,
    test_size=TEST_SIZE,
    random_state=SEED,
    stratify=balanced_df[LABEL_COLUMN],
)

train_text_raw = train_df[TEXT_COLUMN].astype(str).reset_index(drop=True)
test_text_raw = test_df[TEXT_COLUMN].astype(str).reset_index(drop=True)
train_labels_raw = train_df[LABEL_COLUMN].astype(str).reset_index(drop=True)
test_labels_raw = test_df[LABEL_COLUMN].astype(str).reset_index(drop=True)

print("\nTrain size:", train_text_raw.shape)
print("Test size:", test_text_raw.shape)


# -----------------------------
# 9. Label Encoding
# -----------------------------

label_encoder = LabelEncoder()
label_encoder.fit(train_labels_raw)

class_names = list(label_encoder.classes_)
N_CLASSES = len(class_names)

train_y_labels = label_encoder.transform(train_labels_raw)
test_y_labels = label_encoder.transform(test_labels_raw)

train_y_categorical = to_categorical(train_y_labels, N_CLASSES)
test_y_categorical = to_categorical(test_y_labels, N_CLASSES)

print("\nClass names:", class_names)
print("Number of classes:", N_CLASSES)


# -----------------------------
# 10. Neural Model Text Tokenization
# -----------------------------

# For neural models, we use the raw text after light normalization only.
# This preserves sequence information better than aggressive stemming.
train_text_neural = train_text_raw.apply(normalize_arabic)
test_text_neural = test_text_raw.apply(normalize_arabic)

tokenizer = Tokenizer(
    num_words=MAX_NB_WORDS,
    char_level=False,
    filters='”،,.":!"~{#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',
)

tokenizer.fit_on_texts(train_text_neural)
train_sequences = tokenizer.texts_to_sequences(train_text_neural)
test_sequences = tokenizer.texts_to_sequences(test_text_neural)

word_index = tokenizer.word_index
print(f"\nFound {len(word_index):,} unique tokens in the training set.")

sequence_lengths = [len(s) for s in train_sequences]
print(f"Average sequence length: {np.mean(sequence_lengths):.1f}")
print(f"Maximum sequence length: {np.max(sequence_lengths):,}")

x_train_seq = pad_sequences(train_sequences, maxlen=MAX_SEQUENCE_LENGTH)
x_test_seq = pad_sequences(test_sequences, maxlen=MAX_SEQUENCE_LENGTH)

print("x_train_seq shape:", x_train_seq.shape)
print("x_test_seq shape:", x_test_seq.shape)


# -----------------------------
# 11. Zipf's Law Plot
# -----------------------------

words = np.array(list(tokenizer.word_index.keys()))
word_counts = np.array([tokenizer.word_counts[w] for w in words])
word_count_logs = np.log10(word_counts)

plt.figure()
plt.plot(np.arange(1, len(word_count_logs) + 1), word_count_logs)
plt.title("Zipf's Law: Log Word Frequency by Rank")
plt.xlabel("Word Rank")
plt.ylabel("Log10 Frequency")
plt.tight_layout()
plt.savefig(FIGURE_DIR / "zipfs_law.png", dpi=300)
plt.show()

print("\nTop 10 words:", words[:10])
print("Top 10 word frequencies:", word_counts[:10])


# -----------------------------
# 12. Model 1: Deep Neural Network
# -----------------------------

def build_dnn_model():
    """Build a simple embedding-based DNN with global average pooling."""
    sequence_input = Input(shape=(MAX_SEQUENCE_LENGTH,), dtype="int32")

    embedding_layer = Embedding(
        input_dim=MAX_NB_WORDS,
        output_dim=EMBEDDING_DIM,
        input_length=MAX_SEQUENCE_LENGTH,
        trainable=True,
    )

    embedded_sequences = embedding_layer(sequence_input)
    average = GlobalAveragePooling1D()(embedded_sequences)
    predictions = Dense(N_CLASSES, activation="softmax")(average)

    model = Model(sequence_input, predictions, name="DNN_Embedding_AveragePooling")
    model.compile(
        loss="categorical_crossentropy",
        optimizer="adam",
        metrics=["accuracy"],
    )

    return model


dnn_model = build_dnn_model()
dnn_model.summary()

dnn_callbacks = [
    EarlyStopping(monitor="val_loss", patience=3, restore_best_weights=True),
    ModelCheckpoint(
        filepath=str(MODEL_DIR / "best_dnn_model.keras"),
        monitor="val_loss",
        save_best_only=True,
    ),
]

dnn_history = dnn_model.fit(
    x_train_seq,
    train_y_categorical,
    validation_split=VALIDATION_SIZE,
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    callbacks=dnn_callbacks,
    verbose=1,
)

plot_history(dnn_history, "DNN")
dnn_results = evaluate_neural_model(
    dnn_model,
    x_test_seq,
    test_y_categorical,
    test_y_labels,
    class_names,
    "DNN",
)


# -----------------------------
# 13. Model 2: CNN-LSTM
# -----------------------------

def build_cnn_lstm_model():
    """Build a CNN-LSTM model for sequence-based Arabic text classification."""
    sequence_input = Input(shape=(MAX_SEQUENCE_LENGTH,), dtype="int32")

    embedding_layer = Embedding(
        input_dim=MAX_NB_WORDS,
        output_dim=EMBEDDING_DIM,
        input_length=MAX_SEQUENCE_LENGTH,
        trainable=True,
    )

    embedded_sequences = embedding_layer(sequence_input)

    x = Conv1D(filters=64, kernel_size=5, activation="relu")(embedded_sequences)
    x = MaxPooling1D(pool_size=5)(x)
    x = Dropout(0.5)(x)
    x = Conv1D(filters=64, kernel_size=5, activation="relu")(x)
    x = MaxPooling1D(pool_size=5)(x)
    x = Dropout(0.3)(x)
    x = LSTM(32)(x)
    predictions = Dense(N_CLASSES, activation="softmax")(x)

    model = Model(sequence_input, predictions, name="CNN_LSTM")
    model.compile(
        loss="categorical_crossentropy",
        optimizer="adam",
        metrics=["accuracy"],
    )

    return model


cnn_lstm_model = build_cnn_lstm_model()
cnn_lstm_model.summary()

cnn_lstm_callbacks = [
    EarlyStopping(monitor="val_loss", patience=3, restore_best_weights=True),
    ModelCheckpoint(
        filepath=str(MODEL_DIR / "best_cnn_lstm_model.keras"),
        monitor="val_loss",
        save_best_only=True,
    ),
]

cnn_lstm_history = cnn_lstm_model.fit(
    x_train_seq,
    train_y_categorical,
    validation_split=VALIDATION_SIZE,
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    callbacks=cnn_lstm_callbacks,
    verbose=1,
)

plot_history(cnn_lstm_history, "CNN_LSTM")
cnn_lstm_results = evaluate_neural_model(
    cnn_lstm_model,
    x_test_seq,
    test_y_categorical,
    test_y_labels,
    class_names,
    "CNN-LSTM",
)


# -----------------------------
# 14. Classical Model Preprocessing
# -----------------------------

# For classical models, we use stronger preprocessing:
# normalization + stop-word removal + stemming.
train_text_classical = train_text_raw.apply(
    lambda text: preprocess_arabic_text(text, remove_stopwords=True, stem=True)
)
test_text_classical = test_text_raw.apply(
    lambda text: preprocess_arabic_text(text, remove_stopwords=True, stem=True)
)

processed_word_count = train_text_classical.str.split().str.len().sum() + test_text_classical.str.split().str.len().sum()
print(f"\nNumber of words after classical preprocessing: {processed_word_count:,}")


# -----------------------------
# 15. Model 3: SVM with TF-IDF
# -----------------------------

svm_pipeline = Pipeline(
    steps=[
        ("tfidf", TfidfVectorizer(max_features=TFIDF_MAX_FEATURES, analyzer="word")),
        ("svm", SVC(kernel="rbf", random_state=SEED)),
    ]
)

svm_pipeline.fit(train_text_classical, train_labels_raw)
svm_pred_labels_raw = svm_pipeline.predict(test_text_classical)
svm_pred_labels = label_encoder.transform(svm_pred_labels_raw)

svm_results = evaluate_predictions(
    test_y_labels,
    svm_pred_labels,
    class_names,
    "SVM_RBF_TFIDF",
)


# -----------------------------
# 16. Optional Baseline 1: Linear SVM with TF-IDF
# -----------------------------

linear_svm_pipeline = Pipeline(
    steps=[
        ("tfidf", TfidfVectorizer(max_features=TFIDF_MAX_FEATURES, analyzer="word")),
        ("linear_svm", LinearSVC(random_state=SEED)),
    ]
)

linear_svm_pipeline.fit(train_text_classical, train_labels_raw)
linear_svm_pred_raw = linear_svm_pipeline.predict(test_text_classical)
linear_svm_pred = label_encoder.transform(linear_svm_pred_raw)

linear_svm_results = evaluate_predictions(
    test_y_labels,
    linear_svm_pred,
    class_names,
    "Linear_SVM_TFIDF",
)


# -----------------------------
# 17. Optional Baseline 2: Logistic Regression with TF-IDF
# -----------------------------

logreg_pipeline = Pipeline(
    steps=[
        ("tfidf", TfidfVectorizer(max_features=TFIDF_MAX_FEATURES, analyzer="word")),
        (
            "logreg",
            LogisticRegression(
                max_iter=1000,
                random_state=SEED,
                multi_class="auto",
            ),
        ),
    ]
)

logreg_pipeline.fit(train_text_classical, train_labels_raw)
logreg_pred_raw = logreg_pipeline.predict(test_text_classical)
logreg_pred = label_encoder.transform(logreg_pred_raw)

logreg_results = evaluate_predictions(
    test_y_labels,
    logreg_pred,
    class_names,
    "Logistic_Regression_TFIDF",
)


# -----------------------------
# 18. Optional Baseline 3: Multinomial Naive Bayes with TF-IDF
# -----------------------------

nb_pipeline = Pipeline(
    steps=[
        ("tfidf", TfidfVectorizer(max_features=TFIDF_MAX_FEATURES, analyzer="word")),
        ("nb", MultinomialNB()),
    ]
)

nb_pipeline.fit(train_text_classical, train_labels_raw)
nb_pred_raw = nb_pipeline.predict(test_text_classical)
nb_pred = label_encoder.transform(nb_pred_raw)

nb_results = evaluate_predictions(
    test_y_labels,
    nb_pred,
    class_names,
    "Naive_Bayes_TFIDF",
)


# -----------------------------
# 19. Summary Results Table
# -----------------------------

all_results = [
    svm_results,
    linear_svm_results,
    logreg_results,
    nb_results,
    dnn_results,
    cnn_lstm_results,
]

results_df = pd.DataFrame(all_results)
results_df = results_df.sort_values(by="Macro F1", ascending=False).reset_index(drop=True)

print("\n" + "=" * 70)
print("Final Results Summary")
print("=" * 70)
print(results_df)

results_df.to_csv(OUTPUT_DIR / "classification_results_summary.csv", index=False)
create_latex_results_table(results_df, OUTPUT_DIR / "classification_results_table.tex")


# -----------------------------
# 20. Save Models and Encoders
# -----------------------------

import joblib

joblib.dump(svm_pipeline, MODEL_DIR / "svm_rbf_tfidf_pipeline.joblib")
joblib.dump(linear_svm_pipeline, MODEL_DIR / "linear_svm_tfidf_pipeline.joblib")
joblib.dump(logreg_pipeline, MODEL_DIR / "logistic_regression_tfidf_pipeline.joblib")
joblib.dump(nb_pipeline, MODEL_DIR / "naive_bayes_tfidf_pipeline.joblib")
joblib.dump(label_encoder, MODEL_DIR / "label_encoder.joblib")

dnn_model.save(MODEL_DIR / "final_dnn_model.keras")
cnn_lstm_model.save(MODEL_DIR / "final_cnn_lstm_model.keras")

print("\nSaved outputs to:", OUTPUT_DIR.resolve())


# -----------------------------
# 21. Example Predictions
# -----------------------------

def predict_text_examples(text_examples, model_type="svm"):
    """Predict labels for raw Arabic text examples using a selected model."""
    if isinstance(text_examples, str):
        text_examples = [text_examples]

    if model_type == "svm":
        processed = [preprocess_arabic_text(t, remove_stopwords=True, stem=True) for t in text_examples]
        preds = svm_pipeline.predict(processed)
        return preds

    if model_type == "dnn":
        normalized = [normalize_arabic(t) for t in text_examples]
        seq = tokenizer.texts_to_sequences(normalized)
        padded = pad_sequences(seq, maxlen=MAX_SEQUENCE_LENGTH)
        probs = dnn_model.predict(padded, verbose=0)
        preds = label_encoder.inverse_transform(np.argmax(probs, axis=1))
        return preds

    if model_type == "cnn_lstm":
        normalized = [normalize_arabic(t) for t in text_examples]
        seq = tokenizer.texts_to_sequences(normalized)
        padded = pad_sequences(seq, maxlen=MAX_SEQUENCE_LENGTH)
        probs = cnn_lstm_model.predict(padded, verbose=0)
        preds = label_encoder.inverse_transform(np.argmax(probs, axis=1))
        return preds

    raise ValueError("model_type must be one of: 'svm', 'dnn', or 'cnn_lstm'.")


example_text = "من علوم الشعر عند العرب"
print("\nExample prediction using SVM:", predict_text_examples(example_text, model_type="svm"))
print("Example prediction using DNN:", predict_text_examples(example_text, model_type="dnn"))
print("Example prediction using CNN-LSTM:", predict_text_examples(example_text, model_type="cnn_lstm"))

!zip -r arabic_text_classification_outputs.zip arabic_text_classification_outputs